### ISSUE TITLE
Can we geocode transactions

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/CampaignFinanceDataPipeline#8]
We have millions of transactions, this won't be cheap, fast, and easy.

**Comment by davidpeckham** [comment]
What if we used the paid geocode service from [OpenCage](https://opencagedata.com) to get through the backlog of historical transactions, and then switched to their free service (up to 2,200 hits a day, 75K hits a month) or MapBox (up to 100K hits/month) to keep up with quarterly transaction updates? We'd need a scheduled service on our end to batch process transactions daily.

How many transactions do we already have? How many new transactions per quarter? I haven't found the dataset yet, so when I find that I can answer these myself.

**Comment by davidpeckham** [comment]
I see that Code for America Labs is organized as a 501(c3), so maybe the national organization could help us get an Esri [non-profit license:](https://www.esri.com/en-us/industries/sustainability/nonprofit-program/eligibility?rsource=https%3A%2F%2Fwww.esri.com%2Fen-us%2Fsolutions%2Findustries%2Fsustainability%2Fnonprofit-program%2Feligibility#Agreements). The non-profit license includes service credits that we could spend on their [Python-friendly online bulk geocoder](https://developers.arcgis.com/python/guide/batch-geocoding/).

> The Esri Nonprofit Organization Program (NPOP) is designed to provide qualified nonprofit organizations with an affordable way to acquire Esri solutions. All applicants undergo a review process upon submission of the NPOP application that considers formal tax-exempt status and the mission of the organization. In the United States, this is signified by your 501(c3) designation and National Taxonomy of Exempt Entities (NTEE) category. For international applicants, your organization’s eligibility and tax-exempt verification will be determined by your local Esri distributor as part of the application process.
> 
> NPOs generally considered for NPOP membership include noncommercial entities with humanitarian, conservation, and community services missions. Commercial, governmental, or organizations with a primary focus on economic development, as well as primary, secondary, or higher education institutions are not eligible for the NPOP. While educational service organizations with a specific conservation, humanitarian or community service mission may qualify, we strongly encourage universities and other higher education organizations to explore Esri’s GIS for Education programs.

**Comment by davidpeckham** [comment]
Here is a [roundup of geocoding services](https://www.neighborhoodindicators.org/sites/default/files/publications/Geocoding_Options_2017_0.pdf). It's circa 2017, but still a good starting point.

I need to know more about the addresses we need to geocode to understand which of these services would work best (cost, capabilities):

1. How many addresses do we already have?
2. How many do we add each quarter?
3. Are these residential addresses, commercial, or both?
4. Do we need precise latitude and longitude of the address?
5. Do we need to tie these addresses to legislative districts?

I'll try to answer (1) to (3) myself as soon as I get the dataset.

**Comment by ChrisTheDBA** [comment]
There are roughly 1M unique addresses for the accounts in transactions part of the data. Bring in the voter data and we are talking 13M+ for the 2020 snapshot.

Services are thus prohibitively expensive or frustratingly slow because free source limit to 1000-5000 records per batch. 

We need to think of a local geocoder that can be run as part of the ingestion process like Degauss or Pelias. 

other answers. We are not under CFA's 501c3 umbrella, besides using commercial sources like ESRI(particularly ESRI and MS) are discouraged in the larger community.

2. There is an import date that can be used as an indicator of new records. The dedupe/linkage process requires a complete purge and rebuild with the current methods used. But geocoding could be limited to an appropriate subset.
3. Both residental and commercial
4 & 5. We don't have specific requirements for geocoding, but deisgning with the most flexibility for possible uses is best. So lat/long/census divisions/legaslative districts(local, federal)

**Comment by davidpeckham** [comment]
Where is local for us? Do we have cloud infrastructure for apps like Degauss or Pelias?

> We need to think of a local geocoder that can be run as part of the ingestion process like Degauss or Pelias.

**Comment by ChrisTheDBA** [comment]
I guess it was fast easy and cheap/ Downloaded the degauss package and process about 1M account addresses with lat, long, and census block. Tweaking the parameters to get most matches.

**Comment by ChrisTheDBA** [comment]
The degauss docker container process 850K record in 30-40 minutes with a match rate of +95%.

Opening a new ticket to add a code block to the data import to process new records.
